---
title: "PRA Group Assignment"
author: "Group - 5"
date: "06/08/2020"
output: powerpoint_presentation
#output: slidy_presentation
---


## Loading libraries and data
```{r cars, echo = FALSE}
rm(list=ls())
library(forecast)
library(graphics)
library(stats)
library(tseries)
library(forecast)
library(plm)
library(Formula)
library(tcltk)
library(uroot)
library(pdR)
options (scipen=99999)
setwd("D:/Analytics/R/PRA/Datasets")
df=read.csv("png.csv",header = T)
```

## ARIMA modelling
```{r}
str(df)
sum(is.na(df))
nrow(df)

#Plots: Graphs, ACF and PACF-------
##Identification: TREND: Level
tsdisplay(df$Close, lag=50)   #Graph, ACF, PACF

##Unit Root Tests: Trend -----------
k = trunc(length(df$Close)-1)^(1/3)  #k= number of lags
k

adf.test(df$Close, alternative="stationary", k=6)  #Trend Non-stationarity
adf.test(df$Close, alternative="stationary", k=12)

##Identification: First Difference/Trend Differencing

tsdisplay(diff(df$Close,1), lag=50)   #Graph, ACF, PACF
k = trunc((length(diff(df$Close,1))-1)^(1/3))
k
adf.test(diff(df$Close,1), alternative="stationary", k=6)  
adf.test(diff(df$Close,5), alternative="stationary", k=6)  

##Identification: SEASONAL: Seasonal Differencing
tsdisplay(diff(df$Close,5), lag=50)   #Graph, ACF, PACF

##Estimation
fit1 <- Arima(df$Close, order=c(1,0,0), seasonal = list(order = c(1, 1, 1), period=5))
summary(fit1)
fit2 <- Arima(df$Close, order=c(1,0,1), seasonal = list(order = c(4, 1, 0), period=5))
summary(fit2)

##Diagnostics
Box.test(residuals(fit1), lag=5, fitdf=3, type="Ljung")
b2<-tsdiag(fit1)
b2

Box.test(residuals(fit2), lag=10, fitdf=6, type="Ljung")
b2<-tsdiag(fit2)
b2
```

## Exponential Smoothing
```{r}
# Exponential smoothing
##Fit simple exponential smoothing model 
rel_ses <- ses(df$Close)
summary(rel_ses)
#Plot the forecasted values
plot(rel_ses)


##Fit Holt exponential smoothing model 
rel_holt <- holt(df$Close)
summary(rel_holt)
#Plot the forecasted values
plot(rel_holt)

##Fit Holt-Winters exponential smoothing model 
##Converting the df as Time Series
y <- ts(data.matrix(df$Close), start = as.Date("2019-01-01"), end = as.Date ("2019-12-31"), frequency=5)
y
is.ts(y)
str(y)

##Fit with HoltWinters
rel_hw <- HoltWinters(y, seasonal = "mult")
rel_hw
pred <- predict(rel_hw, 50, prediction.interval = TRUE)
plot(rel_hw, pred)
```
```{r}

# OUT OF SAMPLE Forecast
# For ARIMA
hold <- window(ts(df$Close), start=241)
fit1_no_holdout <- Arima(ts(df$Close[-c(241:245)]), order=c(1,0,1),  seasonal = list(order = c(4, 1, 0), period = 5))
fit1_fcast_no_holdout <- forecast(fit1_no_holdout,h=5)
plot(fit1_fcast_no_holdout, main=" ")
lines(ts(df$Close))
summary(fit1_fcast_no_holdout)


# For SES
hold <- window(ts(df$Close), start=241)
fit1_no_holdout <- ses(ts(df$Close[-c(241:245)]))
fit1_fcast_no_holdout <- forecast(fit1_no_holdout,h=5)
plot(fit1_fcast_no_holdout, main=" ")
lines(ts(df$Close))
summary(fit1_fcast_no_holdout)

# For HOLT
hold <- window(ts(df$Close), start=241)
fit1_no_holdout <- holt(ts(df$Close[-c(241:245)]))
fit1_fcast_no_holdout <- forecast(fit1_no_holdout,h=5)
plot(fit1_fcast_no_holdout, main=" ")
lines(ts(df$Close))
summary(fit1_fcast_no_holdout)

# For HOLT Winter
hold <- window(ts(df$Close), start=241)
y <- ts(data.matrix(df$Close), start = as.Date("2019-01-01"), end = as.Date ("2019-12-26"), frequency=5)
fit1_no_holdout <- HoltWinters(y, seasonal = "mult")
fit1_fcast_no_holdout <- forecast(fit1_no_holdout,h=5)
plot(fit1_fcast_no_holdout, main=" ")
lines(ts(df$Close))
summary(fit1_fcast_no_holdout)

```
