---
title: "PRA Group Assignment"
author: "Group - 5"
date: "06/08/2020"
#output: powerpoint_presentation
output: slidy_presentation
---


## Loading libraries and data
```{r cars, echo = FALSE}
rm(list=ls())
library(forecast)
library(graphics)
library(stats)
library(tseries)
library(forecast)
library(plm)
library(Formula)
library(tcltk)
library(uroot)
library(pdR)
options (scipen=99999)
setwd("D:/Analytics/R/PRA/Datasets")
data=read.csv("reliance.csv",header = T)
```

## ARIMA modelling
```{r}
str(data)
sum(is.na(data))
nrow(data)

#Plots: Graphs, ACF and PACF-------
##Identification: TREND: Level
tsdisplay(data$Close, lag=50)   #Graph, ACF, PACF

##Unit Root Tests: Trend -----------
k = trunc(length(data$Close)-1)^(1/3)  #k= number of lags
k

adf.test(data$Close, alternative="stationary", k=6)  #Trend Non-stationarity
adf.test(data$Close, alternative="stationary", k=10)

##Identification: First Difference/Trend Differencing

tsdisplay(diff(data$Close,1), lag=50)   #Graph, ACF, PACF
k = trunc((length(diff(data$Close,1))-1)^(1/3))
k
adf.test(diff(data$Close,1), alternative="stationary", k=6)  
adf.test(diff(data$Close,5), alternative="stationary", k=6)  

##Identification: SEASONAL: Seasonal Differencing
tsdisplay(diff(data$Close,5), lag=50)   #Graph, ACF, PACF

##Estimation
fit1 <- Arima(data$Close, order=c(0,1,0), seasonal = list(order = c(1, 1, 1), period=5))
summary(fit1)
b1<-tsdiag(fit1)

fit2 <- Arima(data$Close, order=c(0,1,0), seasonal = list(order = c(1, 1, 0), period=5))
summary(fit2)
b2<-tsdiag(fit2)

fit3 <- Arima(data$Close, order=c(0,1,0), seasonal = list(order = c(3, 1, 0), period=5))
summary(fit3)
b3<-tsdiag(fit3)

##Diagnostics
tsdisplay(residuals(fit3))
Box.test(residuals(fit3), lag=50, fitdf=3, type="Ljung")

fit4 <- Arima(data$Close, order=c(0,1,0), seasonal = list(order = c(4, 1, 0), period=5))
summary(fit4)
b3<-tsdiag(fit4)

tsdisplay(residuals(fit4))
Box.test(residuals(fit4), lag=50, fitdf=4, type="Ljung")
b2<-tsdiag(fit4)
```

## Exponential Smoothing
```{r}
##Fit simple exponential smoothing model 
rel_ses <- ses(data$Close)
summary(rel_ses)
#Plot the forecasted values
plot(rel_ses)


##Fit Holt exponential smoothing model 
rel_holt <- holt(data$Close)
summary(rel_holt)
#Plot the forecasted values
plot(rel_holt)

##Fit Holt-Winters exponential smoothing model 
##Converting the data as Time Series
y <- ts(data.matrix(data$Close), start = as.Date("2019-01-01"), end = as.Date ("2019-12-31"), frequency=5)

##Fit with hw
rel_hw <- hw(y, h = 10, seasonal = c("additive","multiplicative"))
summary(rel_hw)
#Plot the forecasted values
plot(rel_hw)

##Fit with HoltWinters
rel_hw <- HoltWinters(y, seasonal = "mult")
rel_hw
pred <- predict(rel_hw, 50, prediction.interval = TRUE)
plot(rel_hw, pred)

#Fit automated exponential smoothing model 
rel_auto <- forecast(data$Close, h = 10)

summary(rel_auto)
#Plot the forecasted values
plot(forecast(rel_auto))
```
